[package]
name = "dima-advent-of-code-2024"
version = "1.0.0"
authors = ["Dmitry Kochkin <cooch@mail.ru>"]
edition = "2021"
default-run = "d02v2"

[dependencies]
itertools = "0.12"
once_cell = "1.18.0"
regex = "1.10.2"
